### ISSUE TITLE
LSOpenURLsWithRole error

### ISSUE THREAD

**Issue by iclkevin** [tofi86/universalJavaApplicationStub#3]
Thanks for putting this together and hosting this. I'm substituting the universalJavaApplicationStub into the sample button demo from Oracle's AppBundler demo, and changing the plist executable name accordingly, but I am getting the following error:

LSOpenURLsWithRole() failed with error -10810 for the file

Do you have any idea what this is? Maybe I am doing something wrong?

**Comment by Dylan-M** [comment]
I've come to discover this is because java_home is not being passed the version parameter from the plist file as an argument, and so it's still defaulting to Java 6 when you need something higher.

**Comment by tofi86** [comment]
Alright, `v0.8.0` of this project now has support for the `JVMVersion` Plist key, so go give it a try and add the following to your apple style Plist file:

```
      <key>JVMVersion</key>
      <string>1.6+</string>
```

**Comment by matgessel** [comment]
I got this error because I migrated an older launcher that still had the following config:

`vmoptions="-Xdock:name=Time Tracker"`

I'm launching on Sierra 10.12.6 with JDK 11.0.1. I removed the offending -X option and the app launches fine. 

To troubleshoot this issue, I edited the generated Info.plist directly and deleted chunks of config until the app launched.
