### ISSUE TITLE
Is it possible to provide a hello world sample

### ISSUE THREAD

**Issue by ivanooi** [tofi86/universalJavaApplicationStub#72]
Hi,
  Is there any hello world sample app to dig into? Modify that should be much easier 

Thanks

**Comment by tofi86** [comment]
I'm very sorry for the late reply. However, at the moment I cannot provide any sample due to time limitations.

But you can have a look at one of my OpenSource apps:
https://github.com/paginagmbh/EPUB-Checker/

* uses JarBundler dependency in maven https://github.com/paginagmbh/EPUB-Checker/blob/master/pom.xml#L90-L94
* clone this repo with maven in `target/` https://github.com/paginagmbh/EPUB-Checker/blob/master/pom.xml#L329-L349
* use jarBundler ant task to build the App https://github.com/paginagmbh/EPUB-Checker/blob/master/pom.xml#L351-L390

**Comment by tofi86** [comment]
If you're looking for a "static" example, have a look at my demo app: https://github.com/tofi86/universalJavaApplicationStubDemo
