### ISSUE TITLE
It's obsolete! use jpackage [[maintainers note: maybe not a 100% replacement yet 😉]]

### ISSUE THREAD

**Issue by ddyer0** [tofi86/universalJavaApplicationStub#98]
Great as this script is, jpackage (in jdk15 +) makes it obsolete.  jpackage isn't perfect,
but if you edit the app that jpackage produces and re-sign all the executables, it's
possible to get a java app into the app store.  Someday jpackage may be a 1-stop
solution.

**Comment by tofi86** [comment]
That's kinda true. However, the universalJavaApplicationStub launcher has broader support for JVM detection, also works with _really_ old Apps with either Oracle an Apple Plist syntax and offers a couple more features jpackage does not (at the moment).

This project went live because (among other reasons) Oracle killed their first launcher stub project and I don't want to see this happening again.

>  Someday jpackage may be a 1-stop solution.

Maybe... 

Everyone's free to try jpackage and if it suits their needs, please, go ahead! :-)

I'll leave this issue open for another couple of days/weeks so that people can get informed about jpackage.

**Comment by ebourg** [comment]
jpackage isn't cross platform, it's impossible to create a macOS application bundle on Windows, something that jarbundler+universalJavaApplicationStub supports.
